export const API_BASE_URL = 'http://127.0.0.1:8000';
export const APP_NAME = 'ElitePMS';

export const ACTION_TYPES = {
  NEW_PROJECT: 'NEW_PROJECT',
  ALLOCATION: 'ALLOCATION',
  ASSIGN_TASK: 'ASSIGN_TASK'
};

export const PERFORMANCE_THRESHOLDS = {
  CRITICAL: 100,
  WARNING: 80,
  STABLE: 60
};